[features]
seeds = false
skip-lint = false
resolution = true

[programs.localnet]
ghost_payroll = "BW7Efo8SJQhm5TuAiogpJZPjzNKxc4WQhT8PVhBgpsoa"

[programs.devnet]
ghost_payroll = "BW7Efo8SJQhm5TuAiogpJZPjzNKxc4WQhT8PVhBgpsoa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/mohitthakkar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
